language: perl
perl:
  - 5.12

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq zsh

script:
  - SHELL=$(which bash) bash test/01_bash.t
  - SHELL=$(which zsh) zsh test/02_zsh.t
